version: "3"

services:
    postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true