version: "3"

services:
    redis:
        image: redis:5.0.5-alpine
        ports:
            - 6379:6379
    postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data: